version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./composer.json:/var/www/composer.json 
      - ./composer.lock:/var/www/composer.lock  
    networks:
      - app_network
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000 
    extra_hosts:
      - "host.docker.internal:host-gateway" 

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: todo_list
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  composer:  
    image: composer:latest
    container_name: composer
    working_dir: /var/www
    volumes:
      - .:/var/www 
    networks:
      - app_network
    command: install  

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
