version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www:cached
    networks:
      - app_network
    depends_on:
      - db
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    command: bash -c "composer install --no-interaction --prefer-dist && php artisan serve --host=0.0.0.0 --port=8000"
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=todo_list
      - DB_USERNAME=user
      - DB_PASSWORD=password

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: todo_list
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "todo_list"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
